### PR TITLE
Added a first proposal of the REST API

### PR DESCRIPTION
**Pull request by gulyx**
@NicoloRogaiUNICAM, this is a follow up of my last message (in PR #23).
Please take a look an give me some feedback.

### CODE REVIEW

**Comment by gulyx** [comment]
Hi @brenomiranda, can take a look you too.
I start suspecting that the computation of the LSH should be done locally where the invivo test is supposed to run, and keep remote only the (LSH key stores and the) check is an LSH has been ever observed before.
What do u think?

**Comment by brenomiranda** [comment]
Hi @gulyx,

There are both advantages and disadvantages in computing the minhashing locally.

The advantage is that we need to send the minhashing signature instead of the object representation string to the server. If the minhashing signature is, on average, smaller than the representation string, we can gain some network performance. It does not make sense if they have more or less the same size or if the minhashing signature is bigger than the representation string.

The disadvantage is that we can lose the history of states observed in production if we decide to (or have to) change the number of hashes in the signature. If we have the representation strings we can change the number of hashes (e.g., to adjust the similarity threshold) whenever we want. If we have only the minhashing signatures computed locally, the history is lost if we change the number of hashes.

**Comment by gulyx** [comment]
@brenomiranda I tried to include your suggestion, the API now should be able to receive states as both:
 * internal representation as a string (thus LSH will be computed remotely)
 * LSH representation (thus LSH will be computed locally to the SUT)

@brenomiranda, @NicoloRogaiUNICAM please take a look and let me know.

**Comment by NicoloRogaiUNICAM** [comment]
Hi @gulyx 
I like this solution, the only issue is that the Swagger Editor didn't like the port attribute.
However, it is not giving back compilation problem, it is just ignored from the editor.

**Pull request merged**
